"""Add history table and link to equipment data

Revision ID: 21896a4998be
Revises: 
Create Date: 2025-11-15 04:07:10.289161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21896a4998be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('excel_file_path', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    with op.batch_alter_table('equipment_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('equipment_data_created_by_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'history', ['history_id'], ['history_id'])
        batch_op.drop_column('created_by_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('equipment_data_created_by_user_id_fkey'), 'users', ['created_by_user_id'], ['user_id'])
        batch_op.drop_column('history_id')

    op.drop_table('history')
    # ### end Alembic commands ###
