"""Add History and Announcement tables

Revision ID: 5fddf02839b9
Revises: 3455f59e5fd6
Create Date: 2025-11-15 05:14:42.671510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fddf02839b9'
down_revision = '3455f59e5fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excel_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('excel_file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excel_file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('excel_filename')

    # ### end Alembic commands ###
