"""Add created_by_user_id to equipment_data

Revision ID: bbe4d7fd0923
Revises: f9e9f0ac40b7
Create Date: 2025-11-15 21:38:03.880502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe4d7fd0923'
down_revision = 'f9e9f0ac40b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('history_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['created_by_user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('history_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_by_user_id')

    # ### end Alembic commands ###
