"""Add role visibility to announcements

Revision ID: f9e9f0ac40b7
Revises: 5fddf02839b9
Create Date: 2025-11-15 05:32:33.266659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e9f0ac40b7'
down_revision = '5fddf02839b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_to_manager', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('visible_to_engineer', sa.Boolean(), nullable=False))

    with op.batch_alter_table('equipment_data', schema=None) as batch_op:
        batch_op.alter_column('history_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_data', schema=None) as batch_op:
        batch_op.alter_column('history_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('visible_to_engineer')
        batch_op.drop_column('visible_to_manager')

    # ### end Alembic commands ###
